# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bf59d37403922bfa75dad84d79df0464c91bd33ca159c9908c267bc82424951b853640fcaa062a14292ba3eace1647df171ba818e8098d674605263a3641ffd

test:
  secret_key_base: 158e207daa15098321d1cb66e5bcf3d21cfafe508ed051d04ba64ad775c5661702547aeaefea388bf002a158d4c4832c737088589f7dadc06cbd376e6aadf9a1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
